### ISSUE TITLE
FB share problem

### ISSUE THREAD

**Issue by markormilic** [openfl/extension-share#3]
Hi,
we have implemented openfl-share in our game https://play.google.com/store/apps/details?id=com.phyziko.runningsnake. 
This is the way that we are calling share method:
Share.share("I have just won " + Std.string(game.score) + " points on Running Snake!", "Running Snake", "http://phyziko.com/wp-content/uploads/2014/11/running-snake-512x512.png", "", "", "https://play.google.com/store/apps/details?id=com.phyziko.runningsnake", Share.FACEBOOK);
When I submit FB post from "share intent", none of information(text, subject, image) show up on facebook post, like on the attached images.
![2015-02-18-21-13-09](https://cloud.githubusercontent.com/assets/5919630/6255811/444a783e-b7b3-11e4-8e08-2fd84d030b09.png)
![fbwall](https://cloud.githubusercontent.com/assets/5919630/6255881/c871eb4c-b7b3-11e4-9705-dac14c36d4ae.jpg)

Thanks,
Marko

**Comment by fbricker** [comment]
Hi, I'm not sure how Facebook decides what to display and what to discard. Many times Facebook just takes graph information from the URL and ignores what you send.

I don't know if creating a facebook APP and using the app id in the extension will help on this... On my case I usually create a small website with the information I want to display in the graph information, so that sharing that on facebook looks fine.

Please let me know if you have some experience or knowledge on this kind of facebook sharing that may result useful for the extension :+1: 

Thanks!!!

**Comment by markormilic** [comment]
Hi,
I have tested this with html page but without success. Can you give me an example of html code that you are using for posting?
Thanks in advance,
Marko

**Comment by fbricker** [comment]
Hi, one of my games shares using this URL (www.puralax.com/mobile). So the content comes directly from there.
I've been trying to check how to share things on facebook and to be honest I don't fully understand why they ignore some information. I guess they just want to avoid people from posting generic texts, and that's why they get information automatically from the OG metadata.

I've also made some test for other kind of projects (like inserting a radio player inside facebook) and the only way I made it work was through OG information on a website (try sharing this URL on facebook https://www.muses.org/fb-demo.html).

Anyway, I recommend you to take a look at the information on the source code of www.puralax.com/mobile to see if it helps.

Thanks!

**Comment by fbricker** [comment]
Hi, I just edited the previous comment to fix the URL I was using to share. The URL I'm using is http://www.puralax.com/ (you can see the OG settings there).

**Comment by markormilic** [comment]
Hi,
sorry on delayed answer, we had finished, finally, posting system with the support of your example.

Thanks a lot,
Marko

**Comment by fbricker** [comment]
You're welcome :)
