### ISSUE TITLE
haxelib

### ISSUE THREAD

**Issue by CherryAnt** [openfl/extension-share#6]
haxelib install extension-share says:
No such Project : extension-share

**Comment by ibilon** [comment]
The repository was renamed but the haxelib wasn't yet,
`haxelib install openfl-share`

The readme was updated too soon I guess.

**Comment by fbricker** [comment]
Hi, finally the extension name is "extension-share".
The old "openfl-share" library is now deprecated.

**Comment by Netforza** [comment]
The issue is still present.

haxelib install extension-share says:
No such Project : extension-share

While openfl-share installs correctly.
Is it possible to install extention-share with haxelib?

**Comment by fbricker** [comment]
Hi, yes... I do haxelib install extension-share here and it's working fine.
I'm testing it on different computers and it's working fine (here goes the output)
```
fbricker$ haxelib install extension-share
Downloading extension-share-1,2,2.zip...
Download complete : 46712 bytes in 1.1s (39.4KB/s)
  Created extension/
  Created extension/share/
  Install extension/share/Share.hx
  Install haxelib.json
  Install include.xml
  Created java/
  Created java/ShareEx/
  Install java/ShareEx/include.xml
  Created java/ShareEx/project/
  Created java/ShareEx/project/android/
  Created java/ShareEx/project/android/shareex/
  Install java/ShareEx/project/android/shareex/ShareEx.java
  Created ndll/
  Created ndll/iPhone/
  Install ndll/iPhone/libopenflShareExtension.iphoneos-64.a
  Install ndll/iPhone/libopenflShareExtension.iphoneos-v7.a
  Install ndll/iPhone/libopenflShareExtension.iphonesim-64.a
  Install ndll/iPhone/libopenflShareExtension.iphonesim.a
  Created project/
  Install project/all_objs
  Install project/Build.xml
  Created project/common/
  Install project/common/ExternalInterface.cpp
  Created project/include/
  Install project/include/Share.h
  Created project/ios/
  Install project/ios/.DS_Store
  Install project/ios/Share.mm
  Current version is now 1.2.2
Done
```

Another option you can try, is to manually download the library and install it (you can download the zip version from here: http://lib.haxe.org/p/extension-share/ using any browser but chrome since it's having issues with haxelib right now).

Once you download it, you can do
```
haxelib local extension-share-1.2.2.zip
```

Finally, if the problem persists, you should report the error to haXe directly, as you may have found a bug on haxelib itself.

Thanks!
